### ISSUE TITLE
Create a formula for homebrew

### ISSUE THREAD

**Issue by shmygol** [cruft/cruft#121] opened 2021-08-15 17:37 UTC
Do you consider to create a formula for homebrew to make it easer to use it on non-python projects? Cookiecutter for instance has one.

**Comment by samj1912** [comment] 2021-08-15 18:08
Duplicate of #119. I personally do not have the expertise to maintain a home brew package but I would more than happy if someone else could add one :)

**Closed by samj1912** 2021-08-15 18:08 UTC
