### ISSUE TITLE
Bug: Cruft not applying diff

### ISSUE THREAD

**Issue by jgontrum** [cruft/cruft#86] opened 2021-02-06 12:50 UTC
Hey!

I just discovered cruft and it seems to be the perfect match for my use-case where I regularly have to update many projects with changes from my cookiecutter template.

But something seems to go wrong with the updating. Following scenario:
1. I created a new project with cruft
2. I updated the template
3. I call `cruft update` in the new project
4. Cruft detected a change. If I look at the diff, it looks perfect! Exactly what I want to apply!
5. I confirm the change.
6. **Only the `.cruft.json` is updated with a new commit hash, none of the changes from the diff are applied.**

 I am running version 2.6.0 on Python 3.8.2 on MacOS Catalina if that helps.

Do you have any idea how I can debug this?

**Comment by jgontrum** [comment] 2021-02-06 13:41
Alright, I found the issue: The project was not at the root of git repository:
```
git_repo
  /proj1 <-
  /proj2 
  /proj3
```

That means that the patch command has to include the parameter `--directory=proj1`.

I fixed it by adding a new option to the CLI: https://github.com/jgontrum/cruft

**Comment by samj1912** [comment] 2021-03-09 23:32
Seems like a duplicate of #68 which has been fixed.

**Closed by samj1912** 2021-03-09 23:32 UTC
