### ISSUE TITLE
`check` and `update` should not require an explicit `--checkout` each time

### ISSUE THREAD

**Issue by HappyEinara** [cruft/cruft#104] opened 2021-04-04 11:16 UTC
When I started using cruft I assumed that the `checkout` stored in `.cruft.json` would be used implicitly for future `cruft check`s and `update`s. However [this does not appear to be the case](https://github.com/cruft/cruft/blob/master/cruft/_commands/check.py#L21).

Not only is it inconvenient to have to remember the branch I used for any given project (Isn't the point of cruft to remember the template repo and last commit for me? Why not the branch?), it also breaks the pre-commit hook, unless I devise a way to sync the `checkout` from `.cruft.json` [into my `.pre-commit-config.yaml`](https://pre-commit.com/#passing-arguments-to-hooks).

Is this an oversight in cruft's design, or am I wrong to expect cruft to remember and re-use the branch name?

My approach is to use git branches rather than directories to organise different templates in one repo. That way I can (e.g.) use git techniques like `rebase` to propagate changes in my basic python library template through descendant templates: a python application, a python application for Lambda, a python application for Lambda using Fastapi etc. Given this context, the branch I chose to initialise my project with is very much something I want cruft to be re-using.

I note that if I switched to a directory-based approach to organising templates, then cruft would report an update is necessary any time _any_ template in the repo changes; that seems even less appealing. The other alternative is to have a separate repo for every single template, which would work wonderfully as long as the default branch is the `checkout` but means a lot of cruft (ha!) in my Github account. Branch-organised templates is definitely my preferred approach but it needs cruft to consider the `checkout` part of the template definition.

**Comment by samj1912** [comment] 2021-04-05 17:47
Seems like a duplicate of #54

**Closed by samj1912** 2021-04-05 17:47 UTC
