### ISSUE TITLE
Running through update workflow doesn't work as expected

### ISSUE THREAD

**Issue by leeweezee777** [cruft/cruft#73] opened 2020-11-12 07:47 UTC
OS = MacOS 10.15.7
Python = 3.8.2

```
Package         Version  
--------------- ---------
arrow           0.17.0   
binaryornot     0.4.4    
certifi         2020.11.8
chardet         3.0.4    
click           7.1.2    
cookiecutter    1.7.2    
cruft           2.6.0    
gitdb           4.0.5    
GitPython       3.1.11   
idna            2.10     
Jinja2          2.11.2   
jinja2-time     0.2.0    
MarkupSafe      1.1.1    
pip             19.2.3   
poyo            0.5.0    
python-dateutil 2.8.1    
python-slugify  4.0.1    
requests        2.25.0   
setuptools      41.2.0   
six             1.15.0   
smmap           3.0.4    
text-unidecode  1.3      
typer           0.3.2    
urllib3         1.26.1   
```

I have this repo with a very simple cookiecutter:

https://github.com/leeweezee777/mytemplate

`cruft create` works as expected and renders from what is in main on the repo above.  This is where the issue arises.

I make some updates to the README.md in mytemplate.  Now I go back to myprod and execute the follow, this is the actual transcript:

```
$ cruft check
FAILURE: Project's cruft is out of date! Run `cruft update` to clean this mess up.
$ cruft update
Respond with "s" to intentionally skip the update while marking your project as up-to-date or respond with "v" to view the changes that will be applied.
Apply diff and update? (y, n, s, v) [y]: v
diff --git a/var/folders/5x/vcdp112j5v5chvkwfb7dkwx40000gn/T/tmpowly5tdi/current_template/README.md b/var/folders/5x/vcdp112j5v5chvkwfb7dkwx40000gn/T/tmpowly5tdi/new_template/README.md
index 38d6778..07889bf 100644
--- a/var/folders/5x/vcdp112j5v5chvkwfb7dkwx40000gn/T/tmpowly5tdi/current_template/README.md
+++ b/var/folders/5x/vcdp112j5v5chvkwfb7dkwx40000gn/T/tmpowly5tdi/new_template/README.md
@@ -1,3 +1,8 @@
 dimensionx
 
 This is the initial document
+
+* update1
+* update2
+
+# Lexi Belle taint stink = happiness
Respond with "s" to intentionally skip the update while marking your project as up-to-date or respond with "v" to view the changes that will be applied.
Apply diff and update? (y, n, s, v) [y]: y
Good work! Project's cruft has been updated and is as clean as possible!
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .cruft.json

no changes added to commit (use "git add" and/or "git commit -a")
```

Is anybody else experiencing this? Should't it have updated the README.md? Any help would be greatly appreciated, thank you.

**Comment by samj1912** [comment] 2020-11-13 05:20
It looks like the cookiecutter project(myproj) is not in the root directory of the git repository. We currently don't support update for such use cases. Seems like a duplicate of #68. Please follow that issue for updates.

**Closed by samj1912** 2020-11-13 05:20 UTC
