### ISSUE TITLE
Unable to update template if _copy_without_render is used.

### ISSUE THREAD

**Issue by Sharn-konet** [cruft/cruft#179] opened 2022-08-29 03:39 UTC
I've run into an issue where, if I create a repository using a template with [the `_copy_without_render` feature](https://cookiecutter.readthedocs.io/en/2.1.1/advanced/copy_without_render.html), a value error is raised.

To demonstrate it I have made [this repository](https://github.com/Sharn-konet/cruft-issue-example) which has a simple structure. There is an `ignore_me` folder with jinja templating inside of it which does not need to be rendered by `cookiecutter`, so it's ignored in `cookiecutter.json` using `_copy_without_render`. If this simple template is used to create a repo, and then the repo needs to be updated in any way, the following error will occur:

```bash
cruft update
Traceback (most recent call last):

  File "/Users/sharnkonet.reitsma/.local/bin/cruft", line 8, in <module>
    sys.exit(app())

  File "/Users/sharnkonet.reitsma/.local/pipx/venvs/cruft/lib/python3.9/site-packages/cruft/_cli.py", line 237, in update
    if not _commands.update(

  File "/Users/sharnkonet.reitsma/.local/pipx/venvs/cruft/lib/python3.9/site-packages/cruft/_commands/utils/__init__.py", line 14, in wrapper
    return f(*args, **kwargs)

  File "/Users/sharnkonet.reitsma/.local/pipx/venvs/cruft/lib/python3.9/site-packages/cruft/_commands/utils/__init__.py", line 14, in wrapper
    return f(*args, **kwargs)

  File "/Users/sharnkonet.reitsma/.local/pipx/venvs/cruft/lib/python3.9/site-packages/cruft/_commands/update.py", line 63, in update
    _ = utils.generate.cookiecutter_template(

  File "/Users/sharnkonet.reitsma/.local/pipx/venvs/cruft/lib/python3.9/site-packages/cruft/_commands/utils/generate.py", line 40, in cookiecutter_template
    context = _generate_output(cruft_state, Path(repo.working_dir), cookiecutter_input, output_dir)

  File "/Users/sharnkonet.reitsma/.local/pipx/venvs/cruft/lib/python3.9/site-packages/cruft/_commands/utils/generate.py", line 65, in _generate_output
    new_context = generate_cookiecutter_context(

  File "/Users/sharnkonet.reitsma/.local/pipx/venvs/cruft/lib/python3.9/site-packages/cruft/_commands/utils/cookiecutter.py", line 90, in generate_cookiecutter_context
    context = generate_context(

  File "/Users/sharnkonet.reitsma/.local/pipx/venvs/cruft/lib/python3.9/site-packages/cookiecutter/generate.py", line 117, in generate_context
    apply_overwrites_to_context(obj, extra_context)

  File "/Users/sharnkonet.reitsma/.local/pipx/venvs/cruft/lib/python3.9/site-packages/cookiecutter/generate.py", line 67, in apply_overwrites_to_context
    raise ValueError(

ValueError: ['ignore_me/*'] provided for choice variable _copy_without_render, but the choices are ['ignore_me/*'].
```

**Comment by samj1912** [comment] 2022-09-02 12:33
Duplicate of https://github.com/cruft/cruft/issues/166

**Closed by samj1912** 2022-09-02 12:33 UTC
